# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #url: <%= ENV['DATABASE_URL'] %>
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: mymoney_development

test:
  <<: *default
  database: mymoney_test
  

production:
  <<: *default
  database: mymoney_production
  username: mymoney
  password: <%= ENV['MYMONEY_DATABASE_PASSWORD'] %>
